name: TestRegression

on:
  push:
    branches:
      - "lab**"
  pull_request:
    types: [opened, reopened]

  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: "prod"
        description: "Set environment, e.g. `ENV=prod or ENV=shot`"
      arguments:
        required: false
        default: "-m regression"
        description: "pytest additional arguments, e.g. `-m regression`"

jobs:
  playwright:
    name: Regression tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.41.0-jammy
    env:
      AUTH_LOGIN: ${{ secrets.AUTH_LOGIN }}
      AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
    strategy:
      matrix:
        browser: [remote_chrome]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        id: pytest
        run: |
          pytest --env-name=my-env

      - name: Set output
        run: echo "env_name=my-env" >> $GITHUB_ENV

    outputs:
      env_name: ${{ steps.pytest.outputs.env_name }}
